from services.database.add_db_host import add_device
from services.database.connect_db_host import get_connection
from services.database.connect_db_custom import get_connection_custom
from services.database.delete_db_host import delete_device
from services.database.get_db_host import fetch_all_devices 
from services.database.add_db_group import assign_group_to_hosts
from services.database.delete_db_group import delete_group
from services.database.add_db_custom import create_custom_lab_in_db
from services.database.get_db_custom import fetch_all_custom_labs
from services.database.delete_db_custom import delete_custom_lab_in_db
from services.database.update_db_custom import update_custom_lab_in_db