from services.parse.parse_interface import parse_interface
from services.parse.parse_service import parse_result
from services.parse.parse_switchport import parse_switchport
from services.parse.parse_configd_switch import parse_configd
from services.parse.parse_dashboard import parse_dashboard
from services.parse.parse_lab import parse_ansible_output
from services.parse.parse_sh_int_trunk import parse_sh_int_trunk
from services.parse.parse_routes import parse_routes
from services.parse.parse_switch_host import parse_switch_host