from services.parse.parse_interface import parse_interface
from services.parse.parse_service import parse_result
from services.parse.parse_switchport import parse_switchport
from services.parse.parse_configd_switch import parse_configd
from services.parse.parse_dashboard import parse_dashboard
from services.parse.parse_lab import parse_ansible_output
from services.parse.parse_sh_int_trunk import parse_sh_int_trunk
from services.parse.parse_routes import parse_routes
from services.parse.parse_switch_host import parse_switch_host
from services.parse.parse_router_switch import parse_router_switch
from services.parse.parse_config_device import parse_config_device
from services.parse.parse_verify_output import parse_verify_output
from services.parse.parse_show_output import parse_show_output
from services.parse.parse_error_output import parse_error_output