from services.show_command.sh_config_sw import sh_config
from services.show_command.sh_dashboard import sh_dashboard
from services.show_command.sh_ip_int_br import sh_ip_int_br
from services.show_command.sh_ip_int_br_rt import sh_ip_int_br_rt
from services.show_command.sh_swtort import sh_swtort
from services.show_command.sh_int_trunk import sh_int_trunk
from services.show_command.sh_ip_route import sh_ip_route
from services.show_command.sh_sw_host import sh_sw_host
from services.show_command.sh_router_switch import sh_router_switch